export const movies = [
  {
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [28, 53, 80],
    id: 0,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 1472.891,
    poster_path: "/images/poster.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 8,
    vote_count: 1236,
  },
  // {
  //   adult: false,
  //   backdrop_path: "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
  //   genre_ids: [16, 12, 10751, 14, 35],
  //   id: 1,
  //   original_language: "en",
  //   original_title: "The Super Mario Bros. Movie",
  //   overview:
  //     "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
  //   popularity: 7475.651,
  //   poster_path: "/images/mario.jpg",
  //   release_date: "2023-04-05",
  //   title: "The Super Mario Bros. Movie",
  //   video: false,
  //   vote_average: 7.5,
  //   vote_count: 1538,
  // },
  // {
  //   adult: false,
  //   backdrop_path: "/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
  //   genre_ids: [28, 35, 14],
  //   id: 2,
  //   original_language: "en",
  //   original_title: "Shazam! Fury of the Gods",
  //   overview:
  //     'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
  //   popularity: 4888.739,
  //   poster_path: "/images/sazam.jpeg",
  //   release_date: "2023-03-15",
  //   title: "Shazam! Fury of the Gods",
  //   video: false,
  //   vote_average: 6.8,
  //   vote_count: 1307,
  // },
];
